### ISSUE TITLE
Bug of last minute equals to -1

### ISSUE THREAD

**Issue by leandromoreira** [leandromoreira/nginx-lua-redis-rate-measuring#14]
Our current implementation works but it has a silly bug.

```lua
-- at current_minute 0 the past_minute becames -1
local current_minute = math.floor(current_time / 60) % 60
local past_minute = current_minute - 1
```

**Comment by lucasrodcosta** [comment]
Good catch!

Well... Since `past_minute` is limited in range 0-59 and its limits are:
- 59 when `current_minute` is 0
- 0 when `current_minute` is 1
- 1 when `current_minute` is 2
- ...
- 58 when `current_minute` is 59

we could use the following code:

```lua
local past_minute = (current_minute + 59) % 60
```

**Comment by leandromoreira** [comment]
math saves the day
